wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.34.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697208815.524258
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 103
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 103
      3:
      - 5
      - 7
      - 13
      - 14
      - 23
      4: 3.8.13
      5: 0.15.12
      6: 4.34.0
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
